/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as dashboardUsersRouteImport } from './routes/(dashboard)/users'
import { Route as dashboardSitesRouteImport } from './routes/(dashboard)/sites'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'

const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardUsersRoute = dashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardSitesRoute = dashboardSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof authSignInRoute
  '/sites': typeof dashboardSitesRoute
  '/users': typeof dashboardUsersRoute
  '/': typeof dashboardIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/sites': typeof dashboardSitesRoute
  '/users': typeof dashboardUsersRoute
  '/': typeof dashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(dashboard)/sites': typeof dashboardSitesRoute
  '/(dashboard)/users': typeof dashboardUsersRoute
  '/(dashboard)/': typeof dashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sign-in' | '/sites' | '/users' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/sites' | '/users' | '/'
  id:
    | '__root__'
    | '/(auth)'
    | '/(dashboard)'
    | '/(auth)/sign-in'
    | '/(dashboard)/sites'
    | '/(dashboard)/users'
    | '/(dashboard)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/users': {
      id: '/(dashboard)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof dashboardUsersRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/sites': {
      id: '/(dashboard)/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof dashboardSitesRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardRouteRouteChildren {
  dashboardSitesRoute: typeof dashboardSitesRoute
  dashboardUsersRoute: typeof dashboardUsersRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardSitesRoute: dashboardSitesRoute,
  dashboardUsersRoute: dashboardUsersRoute,
  dashboardIndexRoute: dashboardIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
